gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@18.18.2 | darwin | x64
gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/homebrew/Cellar/fdk/64/custom_node_location/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sfrancis/Desktop/email-provider-app/node_modules/ws/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/homebrew/Cellar/fdk/64/custom_node_location/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sfrancis/Library/Caches/node-gyp/18.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sfrancis/Library/Caches/node-gyp/18.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/Cellar/fdk/64/custom_node_location/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/sfrancis/Library/Caches/node-gyp/18.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sfrancis/Desktop/email-provider-app/node_modules/ws',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/bufferutil.cc:15:
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:107:11: error: no template named 'Handle' in namespace 'v8'
  107 |     , v8::Handle<v8::String> opt, bool def) {
      |       ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:122:11: error: no template named 'Handle' in namespace 'v8'
  122 |     , v8::Handle<v8::String> opt) {
      |       ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:128:11: error: no template named 'Handle' in namespace 'v8'
  128 |     , v8::Handle<v8::String> opt
      |       ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:213:5: error: no member named 'ThrowException' in namespace 'v8'
  213 |     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:209:11: note: expanded from macro '_NAN_THROW_ERROR'
  209 |       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      |       ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:213:5: error: no member named 'New' in 'v8::String'
  213 |     _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:209:42: note: expanded from macro '_NAN_THROW_ERROR'
  209 |       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      |                              ~~~~~~~~~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:216:22: error: variable has incomplete type 'void'
  216 |   inline static void NanThrowError(v8::Handle<v8::Value> error) {
      |                      ^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:216:40: error: no member named 'Handle' in namespace 'v8'
  216 |   inline static void NanThrowError(v8::Handle<v8::Value> error) {
      |                                    ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:216:56: error: expected '(' for function-style cast or type construction
  216 |   inline static void NanThrowError(v8::Handle<v8::Value> error) {
      |                                               ~~~~~~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:216:58: error: use of undeclared identifier 'error'
  216 |   inline static void NanThrowError(v8::Handle<v8::Value> error) {
      |                                                          ^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:216:64: error: expected ';' after top level declarator
  216 |   inline static void NanThrowError(v8::Handle<v8::Value> error) {
      |                                                                ^
      |                                                                ;
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:222:65: error: no member named 'New' in 'v8::String'
  222 |     v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
      |                                                     ~~~~~~~~~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:224:65: error: too few arguments to function call, expected 2, have 1
  224 |     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
      |                                       ~~~~~~~~~~~~~~            ^
/Users/sfrancis/Library/Caches/node-gyp/18.18.2/include/node/v8-primitive.h:662:25: note: 'New' declared here
  662 |   static Local<Integer> New(Isolate* isolate, int32_t value);
      |                         ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/bufferutil.cc:15:
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:224:26: error: no member named 'New' in 'v8::String'
  224 |     obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
      |              ~~~~~~~~~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:225:5: error: no matching function for call to 'NanThrowError'
  225 |     NanThrowError(err);
      |     ^~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:212:22: note: candidate function not viable: no known conversion from 'v8::Local<v8::Value>' to 'const char *' for 1st argument
  212 |   inline static void NanThrowError(const char* errmsg) {
      |                      ^             ~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:221:22: note: candidate function not viable: requires 2 arguments, but 1 was provided
  221 |   inline static void NanThrowError(const char *msg, const int errorNumber) {
      |                      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:229:5: error: no member named 'ThrowException' in namespace 'v8'
  229 |     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:209:11: note: expanded from macro '_NAN_THROW_ERROR'
  209 |       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      |       ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:229:5: error: no member named 'New' in 'v8::String'
  229 |     _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:209:42: note: expanded from macro '_NAN_THROW_ERROR'
  209 |       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      |                              ~~~~~~~~~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:233:5: error: no member named 'ThrowException' in namespace 'v8'
  233 |     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:209:11: note: expanded from macro '_NAN_THROW_ERROR'
  209 |       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      |       ~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:233:5: error: no member named 'New' in 'v8::String'
  233 |     _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:209:42: note: expanded from macro '_NAN_THROW_ERROR'
  209 |       v8::ThrowException(fun(v8::String::New(errmsg)));                        \
      |                              ~~~~~~~~~~~~^
/Users/sfrancis/Desktop/email-provider-app/node_modules/nan/nan.h:244:13: error: no member named 'smalloc' in namespace 'node'
  244 |       node::smalloc::FreeCallback callback,
      |       ~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/Cellar/fdk/64/custom_node_location/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Darwin 23.6.0
gyp ERR! command "/opt/homebrew/Cellar/fdk/64/custom_node_location/bin/node" "/opt/homebrew/Cellar/fdk/64/custom_node_location/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sfrancis/Desktop/email-provider-app/node_modules/ws
gyp ERR! node -v v18.18.2
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 
